openapi: 3.1.0
info:
    title: Inpatient
    description: |
      This code is for a template controller class in the Java programming language. It is used to create a RestController that handles requests from the user. It contains four methods: hello, helloUserInfo, helloFeign, and helloFeatureToggleFeign. The hello method takes in a name as a parameter and returns a string with the name, tenant id, user id, tenant name, and user name. The helloUserInfo method takes in a name and returns a UserInfoDTO object with the tenant id, user id, tenant name, and user name. The helloFeign method takes in a pageable object and returns a response entity with a list of items from the mrappClient. The helloFeatureToggleFeign method returns a response entity with a boolean value that indicates whether or not a tenant configuration is enabled using the featureToggleMicroserviceClient.
    version: '1.0'
servers:
    - url: 'http://localhost:3000'
paths:
  /v1/api/hello:
    get:
      summary: Returns a hello message
      parameters:
        - in: query
          name: name
          schema:
            type: string
            default: stranger
      responses:
        '200':
          description: Returns a hello message
  /v1/api/helloUserInfo:
    get:
      summary: Returns a hello message with user info
      parameters:
        - in: query
          name: name
          schema:
            type: string
            default: stranger
      responses:
        '200':
          description: Returns a hello message with user info
  /v1/api/helloFeign:
    get:
      summary: Returns a hello message from a feign client
      parameters:
        - in: query
          name: pageable
          schema:
            type: string
      responses:
        '200':
          description: Returns a hello message from a feign client
  /v1/api/helloFeatureToggle:
    get:
      summary: Returns the feature toggle status
      responses:
        '200':
          description: Returns the feature toggle status