openapi: 3.1.0
info:
    title: Inpatient
    description: |
      This file is the TemplateController class, which contains endpoints that provide various services to its users. The endpoints are as follows:1. hello: This endpoint takes an optional name parameter and returns a string containing the user's tenant id, user id, tenant name and user name.Input: name (optional)Response: String2. helloUserInfo: This endpoint takes an optional name parameter and returns a UserInfoDTO object containing the user's tenant id, user id, tenant name and user name.Input: name (optional)Response: UserInfoDTO3. helloFeign: This endpoint takes a pageable parameter and returns a string containing the response from the mrappClient.Input: pageableResponse: String4. helloFeatureToggle: This endpoint takes no parameters and returns a boolean indicating the value of the configuration from the featureToggleMicroserviceClient.Input: NoneResponse: Boolean
    version: '1.0'
servers:
    - url: 'http://localhost:3000'
paths:
    /hello:
      get:
        description: Returns a hello message
        responses:
          200:
            description: OK
            body:
              application/json:
                example:
                  message: Hello stranger, this is hello from Template Microservice. Tenant id: 76b011f6-25b3-11e7-a0ea-c776ddb51c38. User id: 89044a7a-25b3-11e7-a0ea-c776ddb51c38. Tenant name: MediRecords. User name: John Doe
    /helloUserInfo:
      get:
        description: Returns a UserInfoDTO object
        responses:
          200:
            description: OK
            body:
              application/json:
                example:
                  userId: 89044a7a-25b3-11e7-a0ea-c776ddb51c38
                  userName: John Doe
                  tenantId: 76b011f6-25b3-11e7-a0ea-c776ddb51c38
                  tenantName: MediRecords
    /helloFeign:
      get:
        description: Returns the result of a feign call
        responses:
          200:
            description: OK
            body:
              application/json:
                example:
                  result: The result of the feign call
    /helloFeatureToggle:
      get:
        description: Returns the result of a feature toggle call
        responses:
          200:
            description: OK
            body:
              application/json:
                example:
                  result: true