openapi: 3.1.0
info:
    title: Inpatient
    description: |
      This file is a controller class for a template microservice. It consists of four endpoints that provide different functionalities. The first endpoint is `/hello`, which takes an optional name parameter and returns a response with a greeting to the user, along with the tenant id, user id, tenant name, and user name of the current user. The second endpoint is `/helloUserInfo`, which takes an optional name parameter and returns a response with a UserInfoDTO object containing the tenant id, user id, tenant name, and user name of the current user. The third endpoint is `/helloFeign`, which takes a Pageable parameter and returns a response with the result of a request to a feign client. The fourth endpoint is `/helloFeatureToggle`, which takes no parameters and returns a response with the result of a request to a feature toggle microservice client.
    version: '1.0'
servers:
    - url: 'http://localhost:3000'
paths:
  /v1/api/hello:
    get:
      summary: Get the hello message
      description: Get the hello message from the Template Microservice
      parameters:
        - name: name
          in: query
          description: Name of the user
          required: false
          schema:
            type: string
            default: stranger
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
  /v1/api/helloUserInfo:
    get:
      summary: Get the hello user info
      description: Get the hello user info from the Template Microservice
      parameters:
        - name: name
          in: query
          description: Name of the user
          required: false
          schema:
            type: string
            default: stranger
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfoDTO'
  /v1/api/helloFeign:
    get:
      summary: Get the hello Feign message
      description: Get the hello Feign message from the Template Microservice
      parameters:
        - name: pageable
          in: query
          description: Pageable object
          required: true
          schema:
            type: object
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
  /v1/api/helloFeatureToggle:
    get:
      summary: Get the hello feature toggle message
      description: Get the hello feature toggle message from the Template Microservice
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    UserInfoDTO:
      type: object
      properties:
        userId:
          type: string
        userName:
          type: string
        tenantId:
          type: string
        tenantName:
          type: string