on:
  pull_request: # Trigger the workflow on pull request events
    types: [opened, synchronize] # Run the workflow when pull request is opened or synchronized

jobs:
  chatgpt-analysis: # Define the job
    runs-on: ubuntu-latest # Specify the runner to run the job on
    name: ChatGPT explain code # Job name
    steps:
      - name: ChatGPT explain code # Step name
        uses: Darryl-MediRecords/chatgpt-pipeline-experiment@1.0.6 # Use the ChatGPT Github Actions from cirolini repository
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }} # Get the OpenAI API key from repository secrets
          github_token: ${{ secrets.DARRYL_GITHUB_TOKEN }} # Get the Github Token from repository secrets
          github_pr_id: ${{ github.event.number }} # Get the Github Pull Request ID from the Github event
